import { useRef, useState } from 'react'
import { ExternalLink } from 'lucide-react'
import avatarUrl from '../assets-avatar.png'
import { PageHead } from './PageHead'
import { parseLadmoSave, serializeLadmoSave, type LadmoSave, type SaveParseResult } from '../utils/saveBackup'

export function About({t,reset,exportSave,importSave}:{t:any;reset:()=>void;exportSave:()=>LadmoSave;importSave:(save:LadmoSave)=>void}) {
  const input = useRef<HTMLInputElement>(null), [result,setResult] = useState<SaveParseResult | null>(null), [message,setMessage] = useState('')
  const download = () => { try { const blob = new Blob([serializeLadmoSave(exportSave())], {type:'application/json'}), url = URL.createObjectURL(blob), link = document.createElement('a'); link.href=url; link.download=`ladmo-codex-backup-${new Date().toISOString().slice(0,10)}.json`; link.click(); URL.revokeObjectURL(url); setMessage(t.saveExported) } catch { setMessage(t.tgSaveError) } }
  const readFile = async (file?:File) => { if(!file)return; const parsed=parseLadmoSave(await file.text()); setResult(parsed); setMessage(parsed.ok?t.saveReady:t[`save${parsed.error[0].toUpperCase()}${parsed.error.slice(1)}`]); if(input.current)input.current.value='' }
  const cancel=()=>{setResult(null);setMessage(t.saveCancelled)}, confirm=()=>{if(result?.ok){try { importSave(result.save);setResult(null);setMessage(t.saveImported) } catch { setMessage(t.tgSaveError) }}}
  const preview=result?.ok?result.preview:null
  return <><PageHead eyebrow="NADANERD LIVE" title={t.about} text={t.aboutText}/><section className="about"><img src={avatarUrl}/><div><h2>{t.communityTitle}</h2><p>{t.communityText}</p><p>{t.unofficialText}</p><div className="social"><a href="https://www.youtube.com/@nadanerdlive" target="_blank">YouTube <ExternalLink size={15}/></a><a href="https://www.twitch.tv/nadanerd" target="_blank">Twitch <ExternalLink size={15}/></a></div></div></section><section className="data-box"><h3>{t.backupTitle}</h3><p>{t.backupText}</p><p className="backup-privacy">{t.backupPrivacy}</p><div className="backup-actions"><button className="quiet" onClick={download}>{t.exportProgress}</button><label className="quiet"><span>{t.importProgress}</span><input ref={input} type="file" accept="application/json,.json" onChange={event=>void readFile(event.target.files?.[0])}/></label></div>{message&&<p className="backup-message" role="status">{message}</p>}{preview&&<section className="backup-preview" role="dialog" aria-modal="true" aria-label={t.backupFound}><h4>{t.backupFound}</h4><p>{t.backupReplaceWarning}</p>{preview.removesGoals&&<p role="alert">{t.tgV1Warning}</p>}<dl><div><dt>{t.backupExportedAt}</dt><dd>{new Date(preview.exportedAt).toLocaleString()}</dd></div><div><dt>{t.backupSeals}</dt><dd>{preview.seals}</dd></div><div><dt>{t.backupConditions}</dt><dd>{preview.completedConditions}</dd></div><div><dt>{t.backupInventory}</dt><dd>{preview.inventory}</dd></div><div><dt>{t.tgTitle}</dt><dd>{preview.goals}</dd></div><div><dt>{t.backupLanguage}</dt><dd>{preview.language.toUpperCase()}</dd></div>{preview.ignoredRecords>0&&<div><dt>{t.backupIgnored}</dt><dd>{preview.ignoredRecords}</dd></div>}</dl><div className="backup-actions"><button className="quiet" onClick={cancel}>{t.cancel}</button><button className="primary" onClick={confirm}>{t.importBackup}</button></div></section>}</section><section className="data-box"><h3>{t.localData}</h3><p>{t.localDataText}</p><button className="danger" onClick={reset}>{t.reset}</button></section></>}
