import { useEffect, useMemo, useState } from 'react'
import { dUnitSets } from '../data/dUnitAudit'
import { completedConditionCount, isDUnitConditionCompleted, setProgress, type DUnitProgress } from '../utils/dUnit'
import { dUnitCodexAttributes, dUnitSkillDamageAttribute, dUnitSkillDamageSubtypes, filterDUnitCodexSets } from '../utils/dUnitFilters'
import { PageHead } from './PageHead'
import { DUnitPortraitList } from './DUnitPortraitList'

export function DUnitConditionToggle({ condition, checked, onToggle }: { condition: typeof dUnitSets[number]['conditions'][number]; checked: boolean; onToggle: (value: boolean) => void }) {
  return <label className={'dunit-condition ' + (checked ? 'done' : '')}><input type="checkbox" checked={checked} onChange={event => onToggle(event.target.checked)}/><span><b>{condition.requirement}</b><small>{condition.bonus.rawLabel}</small></span></label>
}
export function DUnitCodex({ t, progress, toggle, requestedSet, consumeRequest }: { requestedSet?:string|null;consumeRequest?:()=>void;t:any; progress:DUnitProgress; toggle:(setId:string,conditionId:string,checked:boolean)=>void }) {
  const [focusedSet,setFocusedSet]=useState<string|null>(null)
  const [query,setQuery]=useState(''), [filter,setFilter]=useState<'all'|'new'|'progress'|'complete'>('all'), [attribute,setAttribute]=useState(''), [skillDamageSubtype,setSkillDamageSubtype]=useState('')
  const attributes=useMemo(()=>dUnitCodexAttributes(dUnitSets),[])
  useEffect(()=>{if(requestedSet){setFocusedSet(requestedSet);setQuery('');setFilter('all');setAttribute('');setSkillDamageSubtype('');consumeRequest?.()}},[requestedSet,consumeRequest])
  const skillDamageSubtypes=useMemo(()=>dUnitSkillDamageSubtypes(dUnitSets),[])
  const visible=useMemo(()=>filterDUnitCodexSets(focusedSet?dUnitSets.filter(set=>set.id===focusedSet):dUnitSets,query,attribute,skillDamageSubtype).filter(set=>{const done=setProgress(progress,set.id); return filter==='all'||filter==='new'&&done===0||filter==='progress'&&done>0&&done<4||filter==='complete'&&done===4}),[focusedSet,progress,query,filter,attribute,skillDamageSubtype])
  const completed=completedConditionCount(progress), completeSets=dUnitSets.filter(set=>setProgress(progress,set.id)===4).length
  return <><PageHead eyebrow="D-UNIT" title={t.dunitCodex} text={t.dunitCodexText}/><div className="dashboard-top dunit-summary"><div><span>{t.dunitSets}</span><b>{dUnitSets.length}</b></div><div><span>{t.dunitConditions}</span><b>{completed} / {dUnitSets.length*4}</b></div><div><span>{t.dunitComplete}</span><b>{completeSets} / {dUnitSets.length}</b></div></div>{focusedSet&&<button className="quiet" onClick={()=>setFocusedSet(null)}>{t.dunitAll}</button>}<section className="dunit-controls"><input aria-label={t.dunitSearch} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.dunitSearch}/><select aria-label={t.dunitFilter} value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="all">{t.dunitAll}</option><option value="new">{t.dunitNew}</option><option value="progress">{t.dunitInProgress}</option><option value="complete">{t.dunitComplete}</option></select><select aria-label={t.attribute} value={attribute} onChange={e=>{setAttribute(e.target.value);if(e.target.value!==dUnitSkillDamageAttribute)setSkillDamageSubtype('')}}><option value="">{t.all}</option>{attributes.map(value=><option key={value}>{value}</option>)}</select>{attribute===dUnitSkillDamageAttribute&&<select aria-label={t.dunitSkillDamageType} value={skillDamageSubtype} onChange={e=>setSkillDamageSubtype(e.target.value)}><option value="">{t.dunitAllSkillDamageTypes}</option>{skillDamageSubtypes.map(value=><option key={value} value={value}>{t.dunitSkillDamageSubtypeLabels[value] ?? value}</option>)}</select>}<span>{visible.length} {t.results}</span></section><section className="dunit-grid">{visible.map(set=>{const done=setProgress(progress,set.id); return <article className="dunit-card" key={set.id}><header><b>{set.name}</b><span>{done}/4 {t.dunitDone}</span></header><DUnitPortraitList setId={set.id} decorative/>{set.conditions.map(condition=><DUnitConditionToggle key={condition.id} condition={condition} checked={isDUnitConditionCompleted(progress,condition)} onToggle={checked=>toggle(set.id,condition.id,checked)}/>)}</article>})}</section></>
}
