import { useMemo, useState } from 'react'
import { ChevronRight, Coins, Lightbulb, Search, Ticket, X } from 'lucide-react'
import { seals } from '../data/seals'
import type { Seal } from '../types'
import { costPerSeal, efficiency, formatValue, levelFor, levelsFor, maxSealsFor, nextLevel, openersFor, valueFor } from '../utils/calculations'
import { matchesAcquisitionFilter, sourcesForName, type AcquisitionFilter } from '../data/acquisitionSources'
import { localizedSealName, matchesLocalizedSealName } from '../data/localizedSealNames'
import type { Lang } from '../App'
import { getSealState } from '../utils/sealState'
import { NumericInput } from './NumericInput'
import { PageHead } from './PageHead'
const attributes = ['AT','HP','DS','DE','HT','CT','BL','EV']
export function SealCodex({t,lang,state,patchState}:{t:any,lang:Lang,state:(id:string)=>ReturnType<typeof getSealState>,patchState:(id:string,patch:Partial<ReturnType<typeof getSealState>>)=>void}){const [query,setQuery]=useState(''),[attribute,setAttribute]=useState(''),[sort,setSort]=useState('bonus'),[source,setSource]=useState<AcquisitionFilter>('all'),[selected,setSelected]=useState<Seal|null>(null); const rows=useMemo(()=>seals.filter(s=>(!attribute||s.attribute===attribute)&&matchesLocalizedSealName(s,query,lang)&&matchesAcquisitionFilter(s.name,source)).sort((a,b)=>sort==='cost'?costPerSeal(a)-costPerSeal(b):sort==='efficiency'?efficiency(b)-efficiency(a):b.masterValue-a.masterValue),[query,attribute,sort,source,lang]); return <><PageHead eyebrow={t.codexEyebrow} title={t.codex} text={t.codexDescription}/><div className="toolbar"><label><Search size={17}/><input placeholder={t.search} value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={attribute} onChange={e=>setAttribute(e.target.value)}><option value="">{t.all}</option>{attributes.map(x=><option key={x}>{x}</option>)}</select><select value={source} onChange={e=>setSource(e.target.value as AcquisitionFilter)}><option value="all">{t.allSources}</option><option value="map">{t.map}</option><option value="dungeon">{t.dungeon}</option><option value="shinjuku">{t.shinjuku}</option><option value="monsterCard">{t.monsterCard}</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="bonus">{t.sortBonus}</option><option value="cost">{t.sortCost}</option><option value="efficiency">{t.sortEfficiency}</option></select><span>{rows.length} {t.results}</span></div><div className="seal-grid">{rows.map(s=><SealCard key={s.id} seal={s} t={t} lang={lang} userState={state(s.id)} onDetails={()=>setSelected(s)} patchState={patch=>patchState(s.id,patch)}/>)}</div>{selected&&<SealModal seal={selected} t={t} lang={lang} userState={state(selected.id)} patchState={patch=>patchState(selected.id,patch)} close={()=>setSelected(null)}/>}</>}
function SealCard({seal,t,lang,userState,onDetails,patchState}:{seal:Seal,t:any,lang:Lang,userState:ReturnType<typeof getSealState>,onDetails:()=>void,patchState:(patch:Partial<ReturnType<typeof getSealState>>)=>void}){return <article className="seal-card"><div className="seal-top"><span className={'attr '+seal.attribute}>{seal.attribute}</span>{userState.hasSeal&&<small className="state-badge">{t.have}</small>}{userState.doNotRecommend&&<small className="state-badge muted">{t.dontRecommend}</small>}</div><h3>{localizedSealName(seal,lang)}</h3><div className="source-tags">{sourcesForName(seal.name).map((source,index)=><small key={index}>{source.type===`map`?t.mapSource:source.type===`dungeon`?t.dungeonSource:source.type===`shinjuku`?t.shinjukuSource:source.card}{source.type===`map`&&source.difficult?` · ${t.difficultFarm}`:``}</small>)}</div><div className="master"><span>{t.master}</span><b>{formatValue(seal.masterValue,seal.attribute)}</b></div><div className="seal-meta"><span><Ticket/> {seal.ticketCost} → {seal.sealsReceived}</span><span><Coins/> {costPerSeal(seal).toLocaleString('pt-BR',{maximumFractionDigits:2})}{t.perSeal}</span></div>{seal.ticketCost>=25&&<p className="warning">{t.high}</p>}<div className="state-actions"><button title={t.possessionTitle} className={userState.hasSeal?'selected':''} onClick={()=>patchState({hasSeal:!userState.hasSeal,quantity:userState.hasSeal?0:Math.max(1,userState.quantity)})}>{userState.hasSeal?t.undo:t.have}</button><button title={t.excludeTitle} className={userState.doNotRecommend?'selected':''} onClick={()=>patchState({doNotRecommend:!userState.doNotRecommend})}>{userState.doNotRecommend?t.undo:t.dontRecommend}</button></div><button className="detail" onClick={onDetails}>{t.details}<ChevronRight size={16}/></button></article>}
function SealModal({seal,t,lang,userState,patchState,close}:{seal:Seal,t:any,lang:Lang,userState:ReturnType<typeof getSealState>,patchState:(patch:Partial<ReturnType<typeof getSealState>>)=>void,close:()=>void}){const current=levelFor(userState.quantity,seal),next=nextLevel(userState.quantity,seal);return <div className="modal-back" onMouseDown={close}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-x" onClick={close}><X/></button><span className={'attr '+seal.attribute}>{seal.attribute}</span><h2>{localizedSealName(seal,lang)}</h2><p>{t.exchangePrefix} <b>{seal.ticketCost} {t.ticket}{seal.ticketCost!==1?'s':''} → {seal.sealsReceived} {t.seal}{seal.sealsReceived!==1?'s':''}</b></p><div className="source-details">{sourcesForName(seal.name).map((source,index)=><div key={index}><b>{source.type===`map`?t.mapSource:source.type===`dungeon`?t.dungeonSource:source.type===`shinjuku`?t.shinjukuSource:source.card}</b><span>{source.type===`map`?(source.difficult?t.difficultFarm:``):source.type===`dungeon`?(source.reward?t.royalBaseReward:source.dungeon):source.type===`shinjuku`?`${source.coinsPerSeal} ${t.coinsPerSeal}`:``}</span></div>)}</div><div className="progression">{levelsFor(seal).map(l=><div key={l.id}><span>{l.label}</span><b>{formatValue(valueFor(seal,l.id),seal.attribute)}</b><small>{l.threshold.toLocaleString()} {t.sealLower} · {openersFor(l.threshold)} {t.openersLower}</small></div>)}</div><div className="own-row"><label>{t.quantity}<NumericInput value={userState.quantity} min={0} max={maxSealsFor(seal)} onValue={quantity=>patchState({quantity,hasSeal:quantity>0||userState.hasSeal})}/></label><div><span>{t.level}</span><b>{current?.label??'—'}</b>{next&&<small>{t.missing} {next.threshold-userState.quantity} {t.toLevel} {next.label}</small>}</div></div>{seal.ticketCost>=25&&<div className="tip"><Lightbulb/>{t.highTip}</div>}</section></div>}
